config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "combos#index"
  resources :combos, only: [:index, :show] do
    member do
      get :subscribe
    end
  end
  resources :order_groups, only: [:show]
end

app/models/application_record.rb
#Date::DAYS_INTO_WEEK
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combo.rb
class Combo < ApplicationRecord
  enum cut_off_week: DateTime::DAYS_INTO_WEEK

  has_many :order_groups
  has_many :subscriptions

  after_update :time_change
  after_create :time_change

  def time_change
    # 如果是修改了当天的截止时间则需要重新执行任务
    if (DateTime.now.strftime('%A') == week) && previous_changes[:cut_off_time]
      BatchGenerateOrderJob.set(wait_until: combo.current_cut_off_time).perform_later(combo, combo.current_cut_off_time)
    end
  end

  def current_cut_off_time
    DateTime.parse(cut_off_week).change(hour: cut_off_time.hour, min: cut_off_time.min)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :order_group
  belongs_to :combo
  belongs_to :subscription

  validates :subscription, :uniqueness => { :scope => :combo_id }
end

app/models/order_group.rb
class OrderGroup < ApplicationRecord
  has_many :orders
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :combo

  has_many :orders

  validates :user_id, :uniqueness => { :scope => :combo_id }

  after_save :check_order_createable

  def check_order_createable
    time = Time.now
    order_group = combo.order_groups.find_by(end_at: nil)
    if time < combo.current_cut_off_time
      GenerateOrderJob.perform_later(self, order_group.id)
    end
  end

  def generate_order order_group_id
    # 用户锁，防止用户balance的validates被绕过
    user.with_lock do
      user.update!(balance: user.balance - combo.price)
      Order.create!(subscription_id: id, user: user, combo: combo, order_group_id: order_group_id)
    end
  rescue Exception
    # make notification to user
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }

  def subscribe? combo
    Subscription.find_by(combo: combo, user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :set_combo, only: [:show, :subscribe]

  def index
    @combos = Combo.all.order(created_at: :desc)

    # 最近订阅的哪些热门套餐
    @hottest_combo = Subscription.where('created_at > ?', Time.now.beginning_of_week - 7.days).order('count(*) desc').group(:combo_id).count
    @hottest = Combo.where(id: @hottest_combo.map{|id, _| id })
  end

  def show
    @order_groups = @combo.order_groups
  end

  def subscribe
    subscription = Subscription.new(combo: @combo, user: current_user)
    unless subscription.save
      flash[:error] = subscription.errors.full_messages
    end
    redirect_to combos_path
  end

  private

  def set_combo
    @combo = Combo.find(params[:id])
  end

  def set_subscribetion
    @subscribetion = Subscription.find_by(combo_id: params[:id], user_id: current_user.id)
  end
end

app/controllers/order_groups_controller.rb
class OrderGroupsController < ApplicationController
  before_action :set_order_group, only: [:show]

  def show
    @orders = @order_group.orders
  end

  private

  def set_order_group
    @order_group = OrderGroup.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/views/combos/_combo.html.erb
<div class="col mb-4">
  <div class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><%= combo.name %></h5>
      <p class="card-text">Price: <%= combo.price %>$</p>
      <p class="card-text">End_at: <%= combo.cut_off_week.capitalize %> <%= combo.cut_off_time.strftime('%H:%M:%S')%></p>
      <p class="card-text"><%= combo.description %></p>
      <% if current_user.subscribe? combo %>
        <button type="button" class="btn btn-primary" disabled>subscribed</button>
      <% else %>
        <a href=<%= subscribe_combo_path(combo) %> type="button" class="btn btn-primary">Subscribe</a>
      <% end %>
      <a href=<%= combo_path(combo) %> type="button" class="btn btn-success">Detail</a>
    </div>
  </div>
</div>

app/views/combos/_hottest_combo.html.erb
<div class="col mb-4">
  <div class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><%= combo.name %>(<%= @hottest_combo[combo.id] %> people subscribe last week)</h5>
      <p class="card-text">Price: <%= combo.price %>$</p>
      <p class="card-text">End_at: <%= combo.cut_off_week.capitalize %> <%= combo.cut_off_time.strftime('%H:%M:%S')%></p>
      <p class="card-text"><%= combo.description %></p>
      <% if current_user.subscribe? combo %>
        <button type="button" class="btn btn-primary" disabled>subscribed</button>
      <% else %>
        <a href=<%= subscribe_combo_path(combo) %> type="button" class="btn btn-primary">Subscribe</a>
      <% end %>
      <a href=<%= combo_path(combo) %> type="button" class="btn btn-success">Detail</a>
    </div>
  </div>
</div>

app/views/combos/index.html.erb
<div>
  <h1>Combos</h1>
</div>
<div class="row row-cols-1 row-cols-md-3">
  <% @combos.each do |combo| %>
    <%= render 'combo', combo: combo %>
  <% end %>
</div>

<div>
  <h1>Hottest Combos</h1>
</div>
<div class="row row-cols-1 row-cols-md-3">
  <% @hottest.each do |combo| %>
    <%= render 'hottest_combo', combo: combo %>
  <% end %>
</div>

app/views/combos/show.html.erb
<div>
  <h1>OrderGroups</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">StartAt</th>
      <th scope="col">EndAt</th>
      <th scope="col">OrderCount</th>
    </tr>
  </thead>
  <tbody>
    <% @order_groups.each do |group|%>
      <tr>
        <td><%= group.start_at %></td>
        <td><%= group.end_at %></td>
        <td><a href=<%= order_group_path(group) %>><%= group.orders.count %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevHubTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/order_groups/show.html.erb
<div>
  <h1>Orders</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">combo_name</th>
      <th scope="col">user</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order|%>
      <tr>
        <td><%= order.combo.name %></td>
        <td><%= order.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>